### ISSUE TITLE
About the principle

### ISSUE THREAD

**Issue by lucasjinreal** [damnever/ChatGPTx.popclipext#10]
May I ask how does the focus automatically return the previous window implemented in typescript?

**Comment by damnever** [comment]
I'm not entirely clear on the question, but it's worth noting that the active application remains unchanged in the README. TypeScript solely manages the logical tasks, such as interpreting the selected text as input, creating a prompt, sending the input to remote AI services, processing the response, and ultimately directing Popclip to display or paste the result.

**Comment by lucasjinreal** [comment]
@damnever Does it a native app or a web extension plugin?


For native, how to register a global listen for app to listen to system text selection?

I am think this because I wondering if flutter can do this or not. It seems flutter are extremely to do this if it is native desktop app

**Comment by damnever** [comment]
I believe you may have posed your question in the wrong place as this is merely an extension for the macOS application, PopClip. Nonetheless, what I can say is implementing such functions could be challenging for non-native applications. However, you can certainly find numerous AI-powered applications with similar functionalities available. Best of luck!

**Comment by damnever** [comment]
I am maintaining this record of deleted comments for others who may share the same interest and might pose the same question.


<img width="630" alt="image" src="https://github.com/damnever/ChatGPTx.popclipext/assets/6223594/2f854b90-2317-4edb-9b28-ef0fd86d6ea5">
